"""Online DPO: generating preference pairs on-the-fly from the current policy.

This module implements Online DPO, which differs from offline DPO in that
preference pairs are generated on-the-fly from the current policy, rather
than using a static dataset. This addresses a key limitation of offline DPO:
the distribution mismatch between the data-generating policy and the policy
being trained.

Components:
- generate_and_score: generate responses from current policy, score with
  reward model, select best/worst as chosen/rejected
- OnlineDPODataset: dynamically created preference pairs from online gen
- OnlineDPOTrainer: generates responses online, then trains with DPO

Why Online DPO?
---------------
In standard (offline) DPO, preference pairs are collected once and reused.
This causes a distribution shift: the data was generated by an older version
of the policy, but we are training the current version. Online DPO fixes this
by generating fresh preference data from the current policy each epoch.

The trade-off is computational cost: generating responses is expensive.
But the quality of training signal is much better because the preference
pairs reflect the current policy's behavior.

Reference: "Direct Preference Optimization: Your Language Model is Secretly
a Reward Model" (Rafailov et al., 2023). Online DPO variant inspired by
"Self-Play Fine-Tuning Converts Weak Language Models to Strong Language
Models" (Chen et al., 2024).
"""

import sys
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Dict, List, Optional, Tuple
from torch.utils.data import Dataset

# Import DPO components from the previous chapter
sys.path.append(os.path.join(os.path.dirname(__file__), "../03_dpo"))
from dpo import compute_log_probs, DPOLoss


def generate_and_score(
    policy: nn.Module,
    reward_model: nn.Module,
    prompt: List[int],
    max_new_tokens: int = 32,
    num_candidates: int = 4,
    temperature: float = 1.0,
) -> Dict[str, torch.Tensor]:
    """Generate multiple responses from the policy, score with reward model,
    and return the best (chosen) and worst (rejected) as a preference pair.

    This is the core of Online DPO: instead of using pre-collected preference
    data, we generate responses from the current policy and use a reward model
    to determine which are better.

    Process:
    1. Generate `num_candidates` responses from the policy using temperature
       sampling.
    2. Score each complete sequence (prompt + response) with the reward model.
    3. Select the highest-scored as "chosen" and lowest as "rejected".
    4. Compute reference log probs using the policy (frozen snapshot).

    Args:
        policy: The current policy model (generates logits given input_ids).
        reward_model: A reward model that scores complete sequences.
        prompt: Token IDs for the prompt (list of ints).
        max_new_tokens: Number of tokens to generate for each response.
        num_candidates: Number of candidate responses to generate.
        temperature: Sampling temperature. Higher = more random.

    Returns:
        Dict with:
            - "chosen_input_ids": tensor of [prompt, chosen_response] token IDs
            - "rejected_input_ids": tensor of [prompt, rejected_response] token IDs
            - "chosen_reward": scalar reward for the chosen response
            - "rejected_reward": scalar reward for the rejected response
            - "chosen_ref_log_probs": reference log prob for chosen
            - "rejected_ref_log_probs": reference log prob for rejected
            - "response_start_idx": int, index where response tokens begin
    """
    # Set models to inference mode (standard PyTorch pattern)
    policy.eval()
    reward_model.eval()

    prompt_tensor = torch.tensor(prompt, dtype=torch.long)
    prompt_len = len(prompt)

    # Step 1: Generate multiple candidate responses
    candidates = []
    with torch.no_grad():
        for _ in range(num_candidates):
            # Start with the prompt
            input_ids = prompt_tensor.clone().unsqueeze(0)  # (1, prompt_len)

            # Autoregressive generation
            for _ in range(max_new_tokens):
                logits = policy(input_ids)  # (1, seq, vocab)
                next_token_logits = logits[:, -1, :] / temperature  # (1, vocab)

                # Sample from the distribution
                probs = F.softmax(next_token_logits, dim=-1)
                next_token = torch.multinomial(probs, num_samples=1)  # (1, 1)

                # Append to the sequence
                input_ids = torch.cat([input_ids, next_token], dim=1)

            # input_ids shape: (1, prompt_len + max_new_tokens)
            candidates.append(input_ids.squeeze(0))  # (prompt_len + max_new_tokens,)

    # Step 2: Score each candidate with the reward model
    # All candidates have the same length (prompt_len + max_new_tokens)
    # so they can be stacked into a batch
    candidate_batch = torch.stack(candidates)

    with torch.no_grad():
        rewards = reward_model(candidate_batch)  # (num_candidates,)

    # Step 3: Select chosen (highest reward) and rejected (lowest reward)
    chosen_idx = rewards.argmax().item()
    rejected_idx = rewards.argmin().item()

    chosen_ids = candidates[chosen_idx]
    rejected_ids = candidates[rejected_idx]
    chosen_reward = rewards[chosen_idx]
    rejected_reward = rewards[rejected_idx]

    # Step 4: Compute reference log probs using the policy
    # These are frozen snapshots -- the policy used to generate the responses
    with torch.no_grad():
        chosen_ref_lp = compute_log_probs(
            policy, chosen_ids.unsqueeze(0), prompt_len
        ).squeeze(0)
        rejected_ref_lp = compute_log_probs(
            policy, rejected_ids.unsqueeze(0), prompt_len
        ).squeeze(0)

    return {
        "chosen_input_ids": chosen_ids,
        "rejected_input_ids": rejected_ids,
        "chosen_reward": chosen_reward,
        "rejected_reward": rejected_reward,
        "chosen_ref_log_probs": chosen_ref_lp,
        "rejected_ref_log_probs": rejected_ref_lp,
        "response_start_idx": prompt_len,
    }


class OnlineDPODataset(Dataset):
    """Dataset that generates preference pairs on-the-fly from the current policy.

    Unlike DPODataset which takes pre-existing preference pairs, this dataset
    generates them by:
    1. Running the policy to produce candidate responses for each prompt
    2. Scoring candidates with a reward model
    3. Selecting best/worst as chosen/rejected
    4. Pre-computing reference log probs at generation time

    The dataset can be refreshed to generate new pairs from the (updated)
    policy, which is the key advantage of online DPO.

    Args:
        policy: The current policy model for generating responses.
        reward_model: Reward model for scoring responses.
        prompts: List of prompt token ID lists.
        max_new_tokens: Max tokens to generate per response.
        num_candidates: Number of candidates per prompt.
        temperature: Sampling temperature for generation.
    """

    def __init__(
        self,
        policy: nn.Module,
        reward_model: nn.Module,
        prompts: List[List[int]],
        max_new_tokens: int = 32,
        num_candidates: int = 4,
        temperature: float = 1.0,
    ) -> None:
        self.policy = policy
        self.reward_model = reward_model
        self.prompts = prompts
        self.max_new_tokens = max_new_tokens
        self.num_candidates = num_candidates
        self.temperature = temperature

        # Freeze reward model
        self.reward_model.eval()
        for param in self.reward_model.parameters():
            param.requires_grad = False

        # Generate initial preference pairs
        self._pairs: List[Dict[str, torch.Tensor]] = []
        self.refresh()

    def refresh(self) -> None:
        """Regenerate all preference pairs from the current policy.

        This should be called at the start of each training epoch to get
        fresh preference data reflecting the current policy's behavior.
        """
        self._pairs = []
        for prompt in self.prompts:
            pair = generate_and_score(
                policy=self.policy,
                reward_model=self.reward_model,
                prompt=prompt,
                max_new_tokens=self.max_new_tokens,
                num_candidates=self.num_candidates,
                temperature=self.temperature,
            )
            self._pairs.append(pair)

    def __len__(self) -> int:
        return len(self._pairs)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        """Get a preference pair with pre-computed reference log probs.

        Reference log probs are computed at generation time (during refresh)
        and stored, so this method just returns the stored values.

        Args:
            idx: Index into the prompts list.

        Returns:
            Dict with:
                - "chosen_input_ids": tensor of [prompt, chosen] token IDs
                - "rejected_input_ids": tensor of [prompt, rejected] token IDs
                - "chosen_ref_log_probs": reference log prob for chosen
                - "rejected_ref_log_probs": reference log prob for rejected
                - "response_start_idx": int, where response tokens begin
        """
        pair = self._pairs[idx]
        return {
            "chosen_input_ids": pair["chosen_input_ids"],
            "rejected_input_ids": pair["rejected_input_ids"],
            "chosen_ref_log_probs": pair["chosen_ref_log_probs"],
            "rejected_ref_log_probs": pair["rejected_ref_log_probs"],
            "response_start_idx": pair["response_start_idx"],
        }


class OnlineDPOTrainer:
    """Online DPO Trainer that generates preference data and trains with DPO.

    Combines online generation with DPO training in one loop:
    1. Generate fresh preference pairs from the current policy
    2. Train with DPO loss on the fresh data
    3. Repeat for each epoch

    This addresses the distribution mismatch problem of offline DPO by
    always training on data from the current policy.

    Args:
        model: The policy model (being trained).
        ref_model: The reference model (frozen, for KL baseline).
        reward_model: Reward model for scoring generated responses.
        prompts: List of prompt token ID lists.
        beta: Temperature parameter for DPO loss (typically 0.1-0.5).
        lr: Learning rate for the optimizer.
        max_grad_norm: Max gradient norm for gradient clipping.
        max_new_tokens: Max tokens to generate per response.
        num_candidates: Number of candidate responses per prompt.
        temperature: Sampling temperature for generation.
    """

    def __init__(
        self,
        model: nn.Module,
        ref_model: nn.Module,
        reward_model: nn.Module,
        prompts: List[List[int]],
        beta: float = 0.1,
        lr: float = 5e-7,
        max_grad_norm: float = 1.0,
        max_new_tokens: int = 32,
        num_candidates: int = 4,
        temperature: float = 1.0,
    ) -> None:
        self.model = model
        self.ref_model = ref_model
        self.reward_model = reward_model
        self.prompts = prompts
        self.max_grad_norm = max_grad_norm
        self.max_new_tokens = max_new_tokens
        self.num_candidates = num_candidates
        self.temperature = temperature

        self.dpo_loss = DPOLoss(beta=beta)
        self.optimizer = torch.optim.Adam(self.model.parameters(), lr=lr)

        # Freeze reference model
        self.ref_model.eval()
        for param in self.ref_model.parameters():
            param.requires_grad = False

        # Freeze reward model
        self.reward_model.eval()
        for param in self.reward_model.parameters():
            param.requires_grad = False

    def generate(self) -> OnlineDPODataset:
        """Generate fresh preference pairs from the current policy.

        Creates a new OnlineDPODataset by running the policy to generate
        candidate responses and scoring them with the reward model.

        Returns:
            OnlineDPODataset with fresh preference pairs.
        """
        dataset = OnlineDPODataset(
            policy=self.model,
            reward_model=self.reward_model,
            prompts=self.prompts,
            max_new_tokens=self.max_new_tokens,
            num_candidates=self.num_candidates,
            temperature=self.temperature,
        )
        return dataset

    def train_step(self, batch: Dict[str, torch.Tensor]) -> Dict[str, float]:
        """Perform one DPO training step on a batch of preference pairs.

        Args:
            batch: Dict with:
                - "chosen_input_ids": (batch, seq_len) token IDs for chosen
                - "rejected_input_ids": (batch, seq_len) token IDs for rejected
                - "chosen_ref_log_probs": (batch,) reference log probs for chosen
                - "rejected_ref_log_probs": (batch,) reference log probs for rejected
                - "response_start_idx": (batch,) or scalar, where response begins

        Returns:
            Dict with training metrics ("loss").
        """
        self.model.train()
        self.optimizer.zero_grad()

        # Extract batch components
        chosen_input_ids = batch["chosen_input_ids"]
        rejected_input_ids = batch["rejected_input_ids"]
        ref_chosen_log_probs = batch["chosen_ref_log_probs"]
        ref_rejected_log_probs = batch["rejected_ref_log_probs"]
        response_start_idx = batch["response_start_idx"]

        # Handle scalar vs per-sample response_start_idx
        if response_start_idx.dim() == 0:
            response_start_idx = response_start_idx.item()
        else:
            response_start_idx = response_start_idx[0].item()

        # Compute policy log probs
        policy_chosen_log_probs = compute_log_probs(
            self.model, chosen_input_ids, response_start_idx
        )
        policy_rejected_log_probs = compute_log_probs(
            self.model, rejected_input_ids, response_start_idx
        )

        # Compute DPO loss
        loss = self.dpo_loss(
            policy_chosen_log_probs,
            policy_rejected_log_probs,
            ref_chosen_log_probs,
            ref_rejected_log_probs,
        )

        # Backward and optimize
        loss.backward()

        if self.max_grad_norm > 0:
            torch.nn.utils.clip_grad_norm_(
                self.model.parameters(), self.max_grad_norm
            )

        self.optimizer.step()

        return {"loss": loss.item()}

    def train_epoch(self, batch_size: int = 4) -> Dict[str, float]:
        """Run one full epoch of online DPO training.

        1. Generate fresh preference pairs from the current policy
        2. Train on all pairs in mini-batches
        3. Return average metrics

        Args:
            batch_size: Number of preference pairs per mini-batch.

        Returns:
            Dict with average training metrics ("loss").
        """
        # Generate fresh preference data
        dataset = self.generate()

        # Train on all pairs
        total_loss = 0.0
        num_batches = 0

        for i in range(0, len(dataset), batch_size):
            indices = list(range(i, min(i + batch_size, len(dataset))))
            items = [dataset[j] for j in indices]
            batch = {
                "chosen_input_ids": torch.stack([it["chosen_input_ids"] for it in items]),
                "rejected_input_ids": torch.stack([it["rejected_input_ids"] for it in items]),
                "chosen_ref_log_probs": torch.stack([it["chosen_ref_log_probs"] for it in items]),
                "rejected_ref_log_probs": torch.stack([it["rejected_ref_log_probs"] for it in items]),
                "response_start_idx": torch.tensor([it["response_start_idx"] for it in items]),
            }

            metrics = self.train_step(batch)
            total_loss += metrics["loss"]
            num_batches += 1

        avg_loss = total_loss / max(num_batches, 1)
        return {"loss": avg_loss}
